name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '24 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          repository: fgrelated/gld
          ref: main
          path: data
          
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 3.2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl
          
      - name: Fetch GLD data
        run: |
            wget 'https://api.spdrgoldshares.com/api/v1/historical-archive?product=gld&exchange=NYSE&lang=en' -O gld.xlsx

      - name: Convert GLD xlsx to csv
        run: |
            python data/convert-xlsx.py
            ln -fs "$(grep -l '^29-Feb-2024,18' gld*.csv)" GLD_US_archive_EN.csv

      - name: Make output
        run: |
            mkdir ./public
            cp data/c3* data/d3* ./public/
            ruby data/make-index.rb > ./public/index.html
            
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
